language: go
os:
  - windows
  - linux
  - osx
env:
  - GO111MODULE=on
go_import_path: github.com/myitcvscratch/windowsci

install: "echo no install step required"
go:
  - "1.11.x"
script:
  - go run .
